[project]
name = "oppna-statsliggaren"
version = "0.1.0"
description = "Open data for Swedish regleringsbrev"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "mdformat>=0.7.22",
    "markdownify>=1.2.2",
    "httpx[http2]>=0.28.1",
    "httpx-ip-rotator>=0.1.4",
    "python-dotenv>=1.2.2",
]

[tool.setuptools]
packages = ["services"]
